logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://localhost:9000
    resource:
      url: http://localhost:9001
    admin:
      url: http://localhost:9002
